### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextminingdashboard#19]

**Comment by andreassot10** [comment]
Have cleared 0.3.0 Milestone because this is a dashboard and shouldn't have a manual.

I'm keeping issue open in case we decide to add some technical description of how the Text Mining results are calculated.

**Comment by ChrisBeeley** [comment]
> this is a dashboard and shouldn't have a manual

Hear hear! The voice of good UX

**Comment by andreassot10** [comment]
That's right!

**Comment by andreassot10** [comment]
@ChrisBeeley, are you planning to write anything for the Readme before I release 0.4.0.?

I can write something for you instead. General idea is to say we are doing text mining of patient feedback and that this dashboard translates complex findings into illuminating plots and tables. Maybe something about discoverability versus having the best possible algorithms/analysis.

Let me know what you think.

**Comment by ChrisBeeley** [comment]
Sorry, yes I did mean to but I've been drowning in reticulate deployment, among other things.

If you could write something that would be great, thanks. I may PR towards the end of the project if I want to add anything 🙂
