### ISSUE TITLE
Display whole dashboard title

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextminingdashboard#20]
Shinydashboard hides the full dashboard title:

![image](https://user-images.githubusercontent.com/61313624/107324360-dde44100-6a9f-11eb-99c2-01ca7045e96b.png)

The title of the dashboard is Text Mining of Patient Feedback, but the word "feedback" does not display. This is very annoying.

Increasing `titleWidth` to 400 in `dashboardHeader` pushes the icon that hides/reveal the sidebar to the right:

![image](https://user-images.githubusercontent.com/61313624/107324864-a924b980-6aa0-11eb-933c-bd95bf184a11.png)

This is definitely not the desired behaviour.

Use a smaller font size the only solution?

**Comment by ChrisBeeley** [comment]
I tried putting a line break in, that doesn't work. You can put the title to the right of the icon, but it's a bit hacky https://stackoverflow.com/questions/45176030/add-text-on-right-of-shinydashboard-header

I don't think there is a nice way of doing it
