### ISSUE TITLE
Application does not deploy smoothly on RStudio Connect

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextminingdashboard#27]
Because of the way RStudio Connect works tidytext::get_sentiments() does not work on Connect.

For previous releases I have produced a hack with a different code base, but I will need to do this every time there is a new release. I need to use the golem YAML (or even just connect defined sys variables) file to produce a version of the codebase that works on both local installs and the server.

**Comment by andreassot10** [comment]
@ChrisBeeley, any progress with this? Is it still an issue?

**Comment by andreassot10** [comment]
@ChrisBeeley, does [this ](https://github.com/CDU-data-science-team/experienceAnalysis/commit/f2f48dd4d56a6bcdf68872cdd18b41dacd5dfcd2) close this issue?

If yes, can you please close it?

**Comment by ChrisBeeley** [comment]
It may, but I need to test and deploy first. I will do this next week

**Comment by ChrisBeeley** [comment]
As part of the work on this issue this other issue https://github.com/CDU-data-science-team/pxtextminingdashboard/issues/44 will be resolved
