### ISSUE TITLE
Include link to GitHub on dashboard

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextminingdashboard#28]
Should we include a link to the GitHub on the dashboard? If so we could adopt a canonical way in the team to do this. I've filed an issue on [{experiencesdashboard}](https://github.com/CDU-data-science-team/experiencesdashboard/issues/47) to the same effect

**Comment by Lextuga007** [comment]
Yes, would be good to agree a style - mainly it's where we should put this, at the top or bottom, that type of thing.

**Comment by andreassot10** [comment]
https://github.com/CDU-data-science-team/pxtextminingdashboard/commit/5374e4255fff5cdf8dc8f42c154481e1db58bf15

**Comment by Lextuga007** [comment]
Chris suggested creating this as a 'corner' https://github.com/tholman/github-corners.

**Comment by Lextuga007** [comment]
Also for my own reference, the change is here: https://github.com/CDU-data-science-team/pxtextminingdashboard/commit/5374e4255fff5cdf8dc8f42c154481e1db58bf15

**Comment by ChrisBeeley** [comment]
I like the new corner! Much better than the old one

**Comment by andreassot10** [comment]
@ChrisBeeley, can you please assist with this. Feel free to add the corner if you already know how.

**Comment by ChrisBeeley** [comment]
https://github.com/CDU-data-science-team/experiencesdashboard/commit/289393ec20fd85e4137a06d095125a92ecf4b515
