### ISSUE TITLE
Add table with predictions on unseen data

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextminingdashboard#32]
Need a new tab with predictions on unseen data. So far, dashboard supplied table with predictions for test data only.

**Comment by andreassot10** [comment]
@ChrisBeeley, you said this isn't that urgent/necessary. For the sake of work prioritization, let's clarify how you envisage the whole thing. Would you like the dashboard to have a table with the predicted, unlabelled text (this is different from the test data)? To me, it seems like you have always viewed the ["Predicted text" tab](https://github.com/CDU-data-science-team/pxtextminingdashboard/blob/development/R/mod_predictions_table.R) as a means of visually assessing model performance with the test set. This is different from having another tab with predictions on unlabelled data. Do you want this?

**Comment by ChrisBeeley** [comment]
I think we want both ultimately don't we? Performance on test data and unseen data are both important.

Is it possible to just have a selector at the side of the application that flips between the two, which would mean that no new outputs were necessary?

**Comment by andreassot10** [comment]
I was thinkning of something less complicated than a selector:
- Make what is currently tab "Predicted text"  a "sub-tab" of "Model performance". It may be a good idea to also have the confusion matrix in there.
- Retain the "Predicted text" tab, although replace the table with the predictions on the test dataset with a table with the predictions on unseen data. This would require some reticulation (let's ask Lexico to add this new meaning to their dictionary) in order to have the fitted model make the predictions.

My worry is that a selector would confuse non-technical users, especially now that we are thinking of making the tool more attractive to the lay audience (#36).
