### ISSUE TITLE
Add box to control number of bars in Bigrams bar plots

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/pxtextminingdashboard#39]
This is unacceptable:

![image](https://user-images.githubusercontent.com/61313624/121534812-7a403500-c9f9-11eb-89a0-5aa31182ad2a.png)

In a previous version, we had agreed to produce one set of bar plots for all trusts (#25). The closer we get to the final release, the more I want to fix this.

I will add a control box for users to choose the number of bars.

**Comment by ChrisBeeley** [comment]
I like your open tabs- GitHub, Slack, and Roald Dahl :smile:

**Comment by andreassot10** [comment]
> I like your open tabs- GitHub, Slack, and Roald Dahl 😄

Wait a minute- don't all data scientists have these three tabs open all the time?!
