### ISSUE TITLE
Add in select list to choose from themes and criticalities in first tab

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/pxtextminingdashboard#46]
In previous dashboards there was a pick list of themes to read the feedback of on the "Text classificattion" tab, but now there isn't and it's just a text box you can type in. Is this a deliberate change? I feel it would be better with a selection box.

**Comment by andreassot10** [comment]
@ChrisBeeley, shall I bring back the box in Sentiment Analysis -> Polarity - text too?

**Comment by andreassot10** [comment]
You know what, I'll add the box in both but keep the filters too.

**Comment by ChrisBeeley** [comment]
> @ChrisBeeley, shall I bring back the box in Sentiment Analysis -> Polarity - text too?

Yes but make it multiple = TRUE
